
services:

  # MariaDB
  mariadb:
    container_name: mariadb 
    build:
      context: ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
        DB_USERNAME: ${DB_USERNAME}
        DB_USER_PASS: ${DB_USER_PASS}
    image: mariadb:1.0
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception-network

  # Wordpress with PHP-FPM
  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
      args:
        DB_NAME: ${DB_NAME}
        DB_USERNAME: ${DB_USERNAME}
        DB_USER_PASS: ${DB_USER_PASS}
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: wordpress:1.0
    environment:
      - WP_USERNAME=${WP_USERNAME}
      - WP_USER_PASS=${WP_USER_PASS}
    restart: unless-stopped
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_started
    networks:
     - inception-network

  # Nginx
  nginx:
    container_name: nginx
    image: nginx:1.0
    build:
      context: ./requirements/nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception-network

  # Static website
  website:
    container_name: website
    build:
      context: ./requirements/bonus/static_website
    image: webiste:1.0
    restart: unless-stopped
    ports:
      - "80:80"

  # Ftp server
  ftp:
    container_name: ftp
    build: 
      context: ./requirements/bonus/ftp
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASS=${FTP_PASS}
    image: ftp:1.0
    restart: unless-stopped
    ports:
      - "21:21"
    volumes:
      - wp-data:/var/www/wordpress
    networks:
      - inception-network

  # Adminer
  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
    image: adminer:1.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - inception-network

  # Portainer
  portainer:
    container_name: portainer
    build:
      context: ./requirements/bonus/portainer
    image: portainer:1.0
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception-network

networks:
  inception-network:
    name: inception-network
    driver: bridge

volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      device: /home/dcolucci/data/mariadb/
      o: bind
  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      device: /home/dcolucci/data/wordpress/
      o: bind
  