
services:

  # Nginx
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:1.0
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - my-network

  # Wordpress with PHP-FPM
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:1.0
    restart: unless-stopped
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_USER_PASS=${DB_USER_PASS}
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
     - my-network

  # MariaDB
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:1.0
    restart: unless-stopped
    environment:
      - DB_NAME=${DB_NAME}
      - DB_DEFAULT_ADMIN_NAME=${DB_DEFAULT_ADMIN_NAME}
      - DB_ADMIN_NAME=${DB_ADMIN_NAME}
      - DB_ADMIN_PASS=${DB_ADMIN_PASS}
      - DB_USERNAME=${DB_USERNAME}
      - DB_USER_PASS=${DB_USER_PASS}
    # command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      device: /home/dcolucci/data/mariadb/
      o: bind
  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      device: /home/dcolucci/data/wordpress/
      o: bind
  
