
services:

  # MariaDB
  mariadb:
    container_name: mariadb 
    build:
      context: ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
        DB_USERNAME: ${DB_USERNAME}
        DB_USER_PASS: ${DB_USER_PASS}
    image: mariadb:1.0
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - my-network

  # Wordpress with PHP-FPM
  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
      args:
        DB_NAME: ${DB_NAME}
        DB_USERNAME: ${DB_USERNAME}
        DB_USER_PASS: ${DB_USER_PASS}
        DOMAIN_NAME: ${DOMAIN_NAME}
    environment:
      - WP_USERNAME=${WP_USERNAME}
      - WP_USER_PASS=${WP_USER_PASS}
    image: wordpress:1.0
    restart: unless-stopped
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_started
    networks:
     - my-network

  # Nginx
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:1.0
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      device: /home/dcolucci/data/mariadb/
      o: bind
  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      device: /home/dcolucci/data/wordpress/
      o: bind
  