
services:

  # Nginx
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:1.0
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - my-network

  # Wordpress with PHP-FPM
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:1.0
    restart: unless-stopped
    volumes:
      - wp-data:/var/www/wordpress
    # depends_on:
    #   - mariadb
    networks:
     - my-network

  # # MariaDB
  # mariadb:
  #   build: ./requirements/mariadb
  #   image: mariadb:1.0
  #   restart: always
  #   volumes:
  #     - database: ~/data/...


networks:
  my-network:

volumes:
  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      device: /home/dcolucci/data/wordpress/
  mariadb-data: