#!/bin/bash

if [ ! -d "/var/lib/mysql/wordpress" ]; then
	mariadb << EOF
	CREATE DATABASE IF NOT EXISTS $DB_NAME;
	CREATE USER IF NOT EXISTS '$DB_ADMIN_NAME'@'%' IDENTIFIED BY '$DB_ADMIN_PASS';
	CREATE USER IF NOT EXISTS '$DB_USERNAME'@'%' IDENTIFIED BY '$DB_USER_PASS';
	GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_ADMIN_NAME'@'%';
	GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USERNAME'@'%';
	FLUSH PRIVILEGES;
EOF
fi